server:
    port: 8084

security:
    basic:
        enabled: false

config:
    oauth2:
        clientID: confidential
        clientSecret: secret
        accessTokenUri: http://localhost:8083/oauth/token
        userAuthorizationUri: http://localhost:8083/oauth/authorize
        resourceURI: http://localhost:8082/api/